#!/usr/bin/env node
/**
 * Stage 2 — Wasm Kernel Verification Harness.
 *
 * Loads the tier2-kernel Wasm module, feeds it pre-computed test vectors
 * (generated by generate_vectors.py), and compares the Wasm output against
 * the Python-computed expected values.
 *
 * Usage:
 *   node stage2_test.js [test_vectors.json]
 */

const fs = require("fs");
const path = require("path");

// ─── CLI ──────────────────────────────────────────────────────────────

const vectorsPath =
  process.argv[2] || path.join(__dirname, "stage2", "test_vectors.json");
const wasmPath = path.join(
  __dirname,
  "stage2",
  "target",
  "wasm32-unknown-unknown",
  "release",
  "tier2_kernel.wasm"
);

// ─── Load Wasm module ─────────────────────────────────────────────────

async function loadWasm(filePath) {
  const buf = fs.readFileSync(filePath);
  const { instance } = await WebAssembly.instantiate(buf);
  return instance.exports;
}

// ─── Helpers for writing into Wasm linear memory ───────────────────────

/**
 * Write a Uint8Array into Wasm memory at the given byte offset.
 * Returns the offset for convenience.
 */
function writeBytes(memory, data, offset) {
  const view = new Uint8Array(memory.buffer, offset, data.length);
  view.set(data);
  return offset;
}

/**
 * Write an array of int16 values into Wasm memory (little-endian).
 */
function writeInt16Array(memory, values, offset) {
  const view = new Int16Array(memory.buffer, offset, values.length);
  view.set(values);
  return offset;
}

/**
 * Read an Int16Array from Wasm memory.
 */
function readInt16Array(memory, offset, length) {
  return new Int16Array(memory.buffer, offset, length);
}

// ─── Main test runner ──────────────────────────────────────────────────

async function runTest(vectorsPath) {
  console.log("=== Stage 2: Wasm Kernel Verification ===\n");

  // 1. Load test vectors
  console.log(`[harness] Loading test vectors from ${vectorsPath}...`);
  const vectors = JSON.parse(fs.readFileSync(vectorsPath, "utf-8"));

  const inDim = vectors.in_dim;
  const outDim = vectors.out_dim;
  const weightsLen = vectors.weights_packed_len;
  const biasLen = outDim * 2; // int16 = 2 bytes each
  const inputLen = inDim * 2;
  const outputLen = outDim * 2;

  // Decode base64 weights
  const weightBytes = Uint8Array.from(
    Buffer.from(vectors.weights_base64, "base64")
  );

  const biasValues = new Int16Array(vectors.biases);
  const inputValues = new Int16Array(vectors.inputs);
  const expectedValues = new Int16Array(vectors.expected_outputs);

  console.log(
    `[harness] Layer ${inDim}→${outDim}: ` +
      `${weightsLen} weight bytes, ${outDim} biases, ${inDim} inputs`
  );

  // 2. Load Wasm module
  console.log(`[harness] Loading Wasm module from ${wasmPath}...`);
  const exports = await loadWasm(wasmPath);
  console.log(
    `[harness] Wasm exports: ${Object.keys(exports).join(", ")}`
  );
  console.log(`[harness] Wasm module size: ${fs.statSync(wasmPath).size} bytes`);

  const memory = exports.memory;
  const layerForward = exports.layer_forward;

  // 3. Allocate memory in Wasm linear space
  // We use manual offsets; the module exports __heap_base for safe placement
  let offset = exports.__heap_base.value || 1024;
  const align = (n) => (n + 3) & ~3; // 4-byte alignment

  const weightsOffset = offset;
  offset += weightsLen;
  offset = align(offset);

  const biasOffset = offset;
  offset += biasLen;
  offset = align(offset);

  const inputOffset = offset;
  offset += inputLen;
  offset = align(offset);

  const outputOffset = offset;
  offset += outputLen;

  // Grow memory if needed
  const pagesNeeded = Math.ceil(offset / 65536);
  const currentPages = memory.buffer.byteLength / 65536;
  if (pagesNeeded > currentPages) {
    memory.grow(pagesNeeded - currentPages);
  }

  // 4. Write test data into Wasm memory
  writeBytes(memory, weightBytes, weightsOffset);
  writeInt16Array(memory, biasValues, biasOffset);
  writeInt16Array(memory, inputValues, inputOffset);
  // Clear output region (optional, for deterministic failure detection)
  writeInt16Array(memory, new Int16Array(outDim), outputOffset);

  // 5. Call the kernel (without ReLU first, then with)
  console.log(`[harness] Calling layer_forward (no ReLU)...`);
  layerForward(
    weightsOffset, biasOffset, inputOffset, outputOffset,
    inDim, outDim, 0  // apply_relu = 0
  );

  // 6. Read outputs back
  const wasmOutputs = readInt16Array(memory, outputOffset, outDim);

  // 7. Compare
  let maxDiff = 0;
  let failures = 0;
  for (let i = 0; i < outDim; i++) {
    const diff = Math.abs(wasmOutputs[i] - expectedValues[i]);
    if (diff > maxDiff) maxDiff = diff;
    if (diff !== 0) {
      failures++;
      if (failures <= 5) {
        console.log(
          `  Mismatch at neuron ${i}: wasm=${wasmOutputs[i]}, ` +
            `expected=${expectedValues[i]}, diff=${diff}`
        );
      }
    }
  }

  let allPassed = maxDiff === 0;
  console.log(
    `[harness] No-ReLU: ${allPassed ? "PASS ✓" : "FAIL ✗"}` +
      ` (max diff: ${maxDiff}, mismatches: ${failures}/${outDim})`
  );

  // ── Test with ReLU ──────────────────────────────────────
  // Expected outputs with ReLU = expected values, but negatives zeroed
  const expectedRelu = expectedValues.map(v => v < 0 ? 0 : v);

  // Write fresh inputs (output buffer was overwritten)
  writeInt16Array(memory, inputValues, inputOffset);

  console.log(`[harness] Calling layer_forward (with ReLU)...`);
  layerForward(
    weightsOffset, biasOffset, inputOffset, outputOffset,
    inDim, outDim, 1  // apply_relu = 1
  );

  const wasmReluOutputs = readInt16Array(memory, outputOffset, outDim);

  let reluMaxDiff = 0;
  let reluFailures = 0;
  for (let i = 0; i < outDim; i++) {
    const diff = Math.abs(wasmReluOutputs[i] - expectedRelu[i]);
    if (diff > reluMaxDiff) reluMaxDiff = diff;
    if (diff !== 0) {
      reluFailures++;
      if (reluFailures <= 5) {
        console.log(
          `  Mismatch at neuron ${i}: wasm=${wasmReluOutputs[i]}, ` +
            `expected=${expectedRelu[i]}, diff=${diff}`
        );
      }
    }
  }

  const reluPassed = reluMaxDiff === 0;
  allPassed = allPassed && reluPassed;
  console.log(
    `[harness] ReLU:    ${reluPassed ? "PASS ✓" : "FAIL ✗"}` +
      ` (max diff: ${reluMaxDiff}, mismatches: ${reluFailures}/${outDim})`
  );

  console.log(`\n[harness] Overall: ${allPassed ? "ALL PASSED ✓" : "FAILURES ✗"}`);

  if (!allPassed) process.exitCode = 1;
  return allPassed;
}

// ─── Entry ──────────────────────────────────────────────────────────────

runTest(vectorsPath).catch((err) => {
  console.error("[harness] Fatal error:", err);
  process.exit(1);
});
